### ISSUE TITLE
"mvn package" build fails with test errors

### ISSUE THREAD

**Issue by patrickheck** [performant-software/juxta-service#1]
"mvn package" doesn't run successfully on Ubuntu 12.04.2 System

Maven exits with:
Tests in error: 
  importFile(org.juxtasoftware.service.ImportServiceTest): Failed to load ApplicationContext
  importTei(org.juxtasoftware.service.ImportServiceTest): Failed to load ApplicationContext
  parseWitnessList(org.juxtasoftware.service.WitnessParserTest): Failed to load ApplicationContext
  parseNestedWitnessList(org.juxtasoftware.service.WitnessParserTest): Failed to load ApplicationContext
  simpleCase(org.juxtasoftware.service.ComparisonSetCollatorTest): Failed to load ApplicationContext

Tests run: 22, Failures: 0, Errors: 5, Skipped: 0

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] There are test failures.

**Comment by lfoster** [comment]
I believe that may be an issue with some missing init data in the database, but I can't quite tell from the output snippet you sent. Can you run the package command with the -e switch and send some more details on the failures?

As another option, you could skip the tests with the -DskipTests flag on the build. If it packages correctly, unzip the tar file and try launching the service with the startup.sh script. If the service starts up, kill it and re-package with the tests included. As the DB is now initialized, they should pass.

**Comment by patrickheck** [comment]
That's right - if you build the package with the -DskipTests flag you can create the database and start the service. Then after creating the database another regular build seems to work.

**Comment by patrickheck** [comment]
I'm happy to send you the output of "mvn -e package" as an email if you need that to track the error.

**Comment by lfoster** [comment]
Sure, that would be great.

**Comment by patrickheck** [comment]
you can send me your address to heckp@uni-trier.de if you want.

**Comment by lfoster** [comment]
I split out the db init & seed scripts. On a new checkout first run ini_db.sh from scripts. This will create, seed and grant a user on the juxta_ws database. After it completes, do the normal mvn package. All tests should pass now

This script is also included in the binary bundle so it can be used on server installs as well.
